### ISSUE TITLE
Hub Credits Library

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub-credits#2]
### Goal
Services can charge credits for their actions.

### Requirements

- [ ] On startup read credits.yaml
- [ ]  Provide helpers for checking credit balance
- [ ] Produce deducted credit events which post to the hub-credits topic.
- [ ] Read api to the credits.yaml

X-Organization-Id
X-Credit-Balance

```rust
let credits = CreditClient::new(organization: Uuid, balance: i64)

credits
  .allow(["mintEdition", "solana"])
```

```yaml
mintEdition:
  solana: 3
  polygon: 10
  solanaCompressed: 1
createDrop:
  solana: 4
  polygon: 12
createWallet:
  solana: 1
  polygon: 1
```
